package:
  name: pybtex
  version: !!str 0.18

source:
  fn: pybtex-0.18.tar.bz2
  url: https://pypi.python.org/packages/source/p/pybtex/pybtex-0.18.tar.bz2
  md5: 306457c18eb861ec3f644a7e2df98ae4
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pybtex = pybtex:main
    #
    # Would create an entry point called pybtex that calls pybtex.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - pyyaml >=3.01
    - docutils
    - jinja2
    - pygments

  run:
    - python
    - setuptools
    - pyyaml >=3.01
    - docutils
    - jinja2
    - pygments

test:
  # Python imports
  imports:
    - custom_fixers
    - pybtex
    - pybtex.backends
    - pybtex.bibtex
    - pybtex.charwidths
    - pybtex.database
    - pybtex.database.convert
    - pybtex.database.format
    - pybtex.database.input
    - pybtex.database.output
    - pybtex.docgen
    - pybtex.plugin
    - pybtex.style
    - pybtex.style.formatting
    - pybtex.style.labels
    - pybtex.style.names
    - pybtex.style.sorting
    - pybtex.tests
    - pybtex.tests.bst_parser_test
    - pybtex.tests.data
    - pybtex.tests.database_test

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://pybtex.sourceforge.net/
  license:  MIT License
  summary: 'A BibTeX-compatible bibliography processor in Python'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
